### ISSUE TITLE
finish?

### ISSUE THREAD

**Issue by laity-slf** [RickDW/curriculum-rl#1]
Is this work still being done

**Comment by RickDW** [comment]
Hey! I'm definitely going to finish this, I just haven't had a lot of time because of my coursework. If I remember correctly I did finish implementing the basic setup, but I haven't been able to test it yet (because I didn't have an environment to test it out on). So if you're interested you can try it out yourself, but there's probably a bug or two that I'll need to fix :)

**Comment by laity-slf** [comment]
thanks bro
